-- SKU库存表
CREATE TABLE IF NOT EXISTS `pms_sku_stock` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `product_id` BIGINT NOT NULL COMMENT '商品ID',
  `sku_code` VARCHAR(64) NOT NULL COMMENT 'SKU编码',
  `sp_data` VARCHAR(500) NOT NULL COMMENT 'SKU属性JSON数据',
  `stock` INT NOT NULL DEFAULT 0 COMMENT '库存数量',
  `price` DECIMAL(10,2) NOT NULL COMMENT 'SKU价格',
  `image` VARCHAR(500) DEFAULT NULL COMMENT 'SKU图片',
  `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_sku_code` (`sku_code`),
  KEY `idx_product_id` (`product_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='SKU库存表';
